site_name: Desenvolupament d'interfícies 21-22
site_url: https://fpieseljust.github.io/di21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitat 1 - Programació amb Python:
      - Teoria:
        - Introducció: unitats/1-python/teoria/1 - Introducció.md
        - Control de fluxe: unitats/1-python/teoria/2 - Control de fluxe.md
        - Funcions: unitats/1-python/teoria/3 - Funcions.md
        - Tractament de fitxers: unitats/1-python/teoria/4 - Fitxers.md
        - Errors i excepcions: unitats/1-python/teoria/5 - Excepcions.md
        - Programació oorientada a objectes: unitats/1-python/teoria/6 - POO.md
      - Pràctica 1 - PyGame: 
          - Introducció:  unitats/1-python/pràctiques/1 - PyGame.md
          - Disseny del joc:  unitats/1-python/pràctiques/2 - Disseny.md
          - Sprites:  unitats/1-python/pràctiques/3 - Sprites.md
          - Imatges:  unitats/1-python/pràctiques/4 - Imatges.md
          - Sons:  unitats/1-python/pràctiques/5 - So.md
          - Conclusió:  unitats/1-python/pràctiques/6 - Conclusió.md
          - Tasques:
            - Part obligatòria (30%): unitats/1-python/pràctiques/tasques/1 - Obligatori.md
            - Part d'ampliació - projecte (70%): unitats/1-python/pràctiques/tasques/2 - Projecte.md
            - Qualificació: unitats/1-python/pràctiques/tasques/3 - Qualificació.md
    - Unitat 2 - Introducció a les interfícies d'usuari:
      - Teoria:
        - 1 - Introducció a les interfícies d'usuari: unitats/2-intro-interficies/teoria/1 - Introduccio.md
        - 2 - Usabilitat: unitats/2-intro-interficies/teoria/2 - Usabilitat.md
        - 3 - Pautes de disseny: unitats/2-intro-interficies/teoria/3 - Pautes de Disseny.md
      - Tasques:
        - Activitats: unitats/2-intro-interficies/tasques/1 - Activitats.md
        - Pràctiques: unitats/2-intro-interficies/tasques/2 - Pràctiques.md
      - Enllaços: unitats/2-intro-interficies/enllaços/enllaços.md
    - Qualificació:
      - Criteris: 
        - Rúbriques:  qualificacio/rubrica.md
    - About: about.md
theme:
  name: material
  features:
    - content.code.annotate
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js